[wokwi]
version = 1
firmware = ".pio/build/esp32dev/firmware.bin"
elf = ".pio/build/esp32dev/firmware.elf"

{
  "version": 1,
  "author": "Fire Detection FSM System",
  "editor": "wokwi",
  "parts": [
    { "type": "board-esp32-devkit-c-v4", "id": "esp", "top": -28.8, "left": 830.44, "attrs": {} },
    { "type": "wokwi-breadboard", "id": "bb1", "top": -12.6, "left": 118, "attrs": {} },
    {
      "type": "wokwi-dht22",
      "id": "dht1",
      "top": -278.1,
      "left": 349.8,
      "attrs": { "temperature": "80", "humidity": "100" }
    },
    {
      "type": "wokwi-gas-sensor",
      "id": "mq2",
      "top": -244,
      "left": 185.3,
      "rotate": 90,
      "attrs": {}
    },
    {
      "type": "wokwi-led",
      "id": "ledGreen",
      "top": 217.2,
      "left": 224.6,
      "attrs": { "color": "green" }
    },
    {
      "type": "wokwi-led",
      "id": "ledYellow",
      "top": 265.2,
      "left": 330.2,
      "attrs": { "color": "yellow" }
    },
    {
      "type": "wokwi-led",
      "id": "ledRed",
      "top": 322.8,
      "left": 416.6,
      "attrs": { "color": "red" }
    },
    {
      "type": "wokwi-led",
      "id": "sprinklerLed",
      "top": 380.4,
      "left": 618.2,
      "attrs": { "color": "blue" }
    },
    { "type": "wokwi-buzzer", "id": "buzz1", "top": 367.2, "left": 453, "attrs": {} }
  ],
  "connections": [
    [ "esp:TX", "$serialMonitor:RX", "", [] ],
    [ "esp:RX", "$serialMonitor:TX", "", [] ],
    [ "dht1:SDA", "esp:15", "green", [ "v28.8", "h768.1", "v249.6" ] ],
    [ "mq2:A0", "esp:34", "blue", [] ],
    [ "ledGreen:A", "esp:18", "green", [ "h720", "v-182.4" ] ],
    [ "ledYellow:A", "esp:19", "yellow", [ "h652.8", "v-240" ] ],
    [ "ledRed:A", "esp:21", "red", [ "h595.2", "v-316.8" ] ],
    [ "buzz1:1", "esp:4", "purple", [ "v28.8", "h556.8", "v-355.2" ] ],
    [ "ledGreen:C", "bb1:bn.1", "black", [ "h-76.4", "v-75.5" ] ],
    [ "bb1:tp.50", "esp:3V3", "red", [ "v0" ] ],
    [ "bb1:bn.50", "esp:GND.1", "cyan", [ "h64.4", "v-51.9" ] ],
    [ "mq2:GND", "bb1:tn.9", "black", [ "v0" ] ],
    [ "ledYellow:C", "bb1:bn.13", "black", [ "h-47.6", "v-123.5" ] ],
    [ "ledRed:C", "bb1:bn.23", "black", [ "h-18.8", "v-181.1" ] ],
    [ "dht1:VCC", "bb1:tp.19", "red", [ "v0" ] ],
    [ "bb1:bp.50", "esp:3V3", "red", [ "h56.8", "v-173.7" ] ],
    [ "bb1:tn.50", "esp:GND.1", "cyan", [ "h85.6", "v115.1" ] ],
    [ "mq2:VCC", "bb1:tp.8", "red", [ "v0" ] ],
    [ "dht1:GND", "bb1:tn.21", "black", [ "v0" ] ],
    [ "sprinklerLed:A", "esp:22", "blue", [ "h489.4", "v-402.8" ] ],
    [ "buzz1:2", "bb1:bn.33", "black", [ "h38", "v-267.5" ] ],
    [ "sprinklerLed:C", "bb1:bn.38", "black", [ "h-47.6", "v-238.7" ] ]
  ],
  "dependencies": {}
}